---
title: "AuracleAnalyses_SSIB_2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}


basedir <- ("~/OneDrive - The Pennsylvania State University/Bari-files-Manual-Box-Transfer/00_PennState/Bout_Project")
setwd(file.path(basedir,"Data/Intervals/"))

myfiles = list.files(pattern="*.csv")
list.files()
dat_csv = ldply(myfiles, read_csv)

#### Prepare dataframes ####
# set class of variables
dat_csv$IBI <- as.numeric(dat_csv$IBI)
dat_csv$InterEatInt_f <- as.numeric(dat_csv$InterEatInt_f)
dat_csv$InterEatInt_n <- as.numeric(dat_csv$InterEatInt_n)
dat_csv$chewtimes <- as.numeric(dat_csv$chewtimes)
dat_csv$id <- as.numeric(dat_csv$id)

# Make full ID variable
dat_csv$FullID <- paste(dat_csv$parid, dat_csv$session, dat_csv$Paradigm, sep="_")

# Recode mis-coded variables
# Note: For AUR0076, "eat_f" is coded as "eat" ; "eat_n" is coded as "other chew"
unique(dat_csv$Annotation)
dat_csv$Annotation[dat_csv$Annotation == "eat"] <- "eat_f"
dat_csv$Annotation[dat_csv$Annotation == "drinK"] <- "drink"
dat_csv$Annotation[dat_csv$Annotation == "other chew"] <- "eat_n"

# subset data
full_dat <- subset(dat_csv, Paradigm == "Meal" | Paradigm == "Snack")
full_meals <- subset(dat_csv, Paradigm == "Meal") # This dateframe excludes drinks
full_snacks <- subset(dat_csv, Paradigm == "Snack") # This dateframe excludes drinks

```

## R Markdown

```{r compare IBI distributions for meals}
meals <- full_meals

ID = unique(meals$parid)
KS_summary_meals = data.frame(matrix(rep(NA,8*length(ID)),ncol = 8))
names(KS_summary_meals) = c("ParID", "nsess", "avg_D_WP_tests", "avg_D_BP_tests","n_WP_tests", "n_BP_tests", "n_sig_WP_tests", "n_sig_BP_tests")

### Clean meals database... if # IEI values in a session is < 10, remove session from database ###
for (i in 1:length(ID)) {
  dat = meals[meals$parid == ID[i],]
  nsess = length(unique(dat$session))
  counttable <- data.frame(table(dat$session[!is.na(dat$InterEatInt_n)]))
  
  #if # IEI values in a session is < 10, remove session from database
  for (s in unique(dat$session)) {
    if (counttable[s, "Freq"] <10) {
      dat = dat[dat$session != s,]
      meals = meals[!(meals$parid == ID[i] & meals$session == s ),] 
    }
  }
}

### KS test loop ###
for (i in 1:length(ID)) {
  dat = meals[meals$parid == ID[i],]
  
  # count the number of sessions 
  sessions_vector <- unique(dat$session)
  nsess = length(sessions_vector)
  KS_summary_meals[i,"ParID"] = as.character(ID[i])
  KS_summary_meals[i,"nsess"] = nsess
  
  if (nsess > 1) {
    btw_KS_vector_D = NA
    btw_KS_vector_sig = NA
    num_WP_sig = 0
    
    IEI_1 = dat[dat$session == sessions_vector[1], "InterEatInt_n"]
    IEI_2 = dat[dat$session == sessions_vector[2], "InterEatInt_n"]
    
    KS_d_1.2 = as.numeric(ks.test(IEI_1, IEI_2)$statistic)
    
    if ((ks.test(IEI_1, IEI_2)$p) < 0.001){
      num_WP_sig = num_WP_sig + 1
    }
    
    if (nsess == 2) {
      avg_within_KS_d = KS_d_1.2
      KS_summary_meals[i,"n_WP_tests"] = 1
      KS_summary_meals[i,"n_sig_WP_tests"] = num_WP_sig
      
      
    } else if (nsess == 3) {
      
      IEI_3 = dat[dat$session == sessions_vector[3], "InterEatInt_n"]
      KS_d_1.3 = as.numeric(ks.test(IEI_1, IEI_3)$statistic)
      KS_d_2.3 = as.numeric(ks.test(IEI_2, IEI_3)$statistic)
      
      if ((ks.test(IEI_1, IEI_3)$p) < 0.001){
        num_WP_sig = num_WP_sig + 1 }
      
      if ((ks.test(IEI_2, IEI_3)$p) < 0.001){
        num_WP_sig = num_WP_sig + 1 }
      
      avg_within_KS_d = mean(KS_d_1.2, KS_d_1.3, KS_d_2.3)
      KS_summary_meals[i,"n_WP_tests"] = 2
      KS_summary_meals[i,"n_sig_WP_tests"] = num_WP_sig
    }
    KS_summary_meals[i,"avg_D_WP_tests"] = avg_within_KS_d
    
    
    dat_other = meals[meals$parid != ID[i],]
    
    dat_other_wide = dcast(dat_other, id ~ parid + session, value.var = "InterEatInt_n")
    n_other = ncol(dat_other_wide)
    
    for (s in sessions_vector) {
      for (c in 2:n_other) {
        IEI = dat[dat$session == s, "InterEatInt_n"]
        IEI_other = dat_other_wide[,c]
        btw_KS = as.numeric(ks.test(IEI, IEI_other)$statistic)
        
        #add to vector
        btw_KS_vector_D[c-1] = btw_KS
        
        if (as.numeric(ks.test(IEI, IEI_other)$p) < 0.001) {
          btw_KS_vector_sig[c-1] = "sig"
        }
        else if (as.numeric(ks.test(IEI, IEI_other)$p) >= 0.001)
          btw_KS_vector_sig[c-1] = "NS"
      }
    }
    KS_summary_meals[i,"avg_D_BP_tests"] = mean(btw_KS_vector_D)
    KS_summary_meals[i,"n_BP_tests"] = length(btw_KS_vector_sig)
    KS_summary_meals[i,"n_sig_BP_tests"] = length(which(btw_KS_vector_sig == "sig"))
  }
}

```


```{r compare IBI distributions for snacks}
snacks <- full_snacks

ID = unique(snacks$parid)
KS_summary_snacks = data.frame(matrix(rep(NA,8*length(ID)),ncol = 8))
names(KS_summary_snacks) = c("ParID", "nsess", "avg_D_WP_tests", "avg_D_BP_tests","n_WP_tests", "n_BP_tests", "n_sig_WP_tests", "n_sig_BP_tests")

### Clean snacks database... if # IEI values in a session is < 10, remove session from database ###
for (i in 1:length(ID)) {
  dat = snacks[snacks$parid == ID[i],]
  nsess = length(unique(dat$session))
  counttable <- data.frame(table(dat$session[!is.na(dat$InterEatInt_n)]))
  
  #if # IEI values in a session is < 10, remove session from database
  for (s in unique(dat$session)) {
    if (counttable[s, "Freq"] <10) {
      dat = dat[dat$session != s,]
      snacks = snacks[!(snacks$parid == ID[i] & snacks$session == s ),] 
    }
  }
}

### KS test loop ###
for (i in 1:length(ID)) {
  dat = snacks[snacks$parid == ID[i],]
  
  # count the number of sessions 
  sessions_vector <- unique(dat$session)
  nsess = length(sessions_vector)
  KS_summary_snacks[i,"ParID"] = as.character(ID[i])
  KS_summary_snacks[i,"nsess"] = nsess
  
  if (nsess > 1) {
    btw_KS_vector_D = NA
    btw_KS_vector_sig = NA
    num_WP_sig = 0
    
    IEI_1 = dat[dat$session == sessions_vector[1], "InterEatInt_n"]
    IEI_2 = dat[dat$session == sessions_vector[2], "InterEatInt_n"]
    
    KS_d_1.2 = as.numeric(ks.test(IEI_1, IEI_2)$statistic)
    
    if ((ks.test(IEI_1, IEI_2)$p) < 0.001){
      num_WP_sig = num_WP_sig + 1
    }
    
    if (nsess == 2) {
      avg_within_KS_d = KS_d_1.2
      KS_summary_snacks[i,"n_WP_tests"] = 1
      KS_summary_snacks[i,"n_sig_WP_tests"] = num_WP_sig
      
      
    } else if (nsess == 3) {
      
      IEI_3 = dat[dat$session == sessions_vector[3], "InterEatInt_n"]
      KS_d_1.3 = as.numeric(ks.test(IEI_1, IEI_3)$statistic)
      KS_d_2.3 = as.numeric(ks.test(IEI_2, IEI_3)$statistic)
      
      if ((ks.test(IEI_1, IEI_3)$p) < 0.001){
        num_WP_sig = num_WP_sig + 1 }
      
      if ((ks.test(IEI_2, IEI_3)$p) < 0.001){
        num_WP_sig = num_WP_sig + 1 }
      
      avg_within_KS_d = mean(KS_d_1.2, KS_d_1.3, KS_d_2.3)
      KS_summary_snacks[i,"n_WP_tests"] = 2
      KS_summary_snacks[i,"n_sig_WP_tests"] = num_WP_sig
    }
    KS_summary_snacks[i,"avg_D_WP_tests"] = avg_within_KS_d
    
    
    dat_other = snacks[snacks$parid != ID[i],]
    
    dat_other_wide = dcast(dat_other, id ~ parid + session, value.var = "InterEatInt_n")
    n_other = ncol(dat_other_wide)
    
    for (s in sessions_vector) {
      for (c in 2:n_other) {
        IEI = dat[dat$session == s, "InterEatInt_n"]
        IEI_other = dat_other_wide[,c]
        btw_KS = as.numeric(ks.test(IEI, IEI_other)$statistic)
        
        #add to vector
        btw_KS_vector_D[c-1] = btw_KS
        
        if (as.numeric(ks.test(IEI, IEI_other)$p) < 0.001) {
          btw_KS_vector_sig[c-1] = "sig"
        }
        else if (as.numeric(ks.test(IEI, IEI_other)$p) >= 0.001)
          btw_KS_vector_sig[c-1] = "NS"
      }
    }
    KS_summary_snacks[i,"avg_D_BP_tests"] = mean(btw_KS_vector_D)
    KS_summary_snacks[i,"n_BP_tests"] = length(btw_KS_vector_sig)
    KS_summary_snacks[i,"n_sig_BP_tests"] = length(which(btw_KS_vector_sig == "sig"))
  }
}

```


Meal_Event_in_percentage_interval_10 was generated by Event_in_interval.R script 
Meals were divided into 10 increments)

```{r cumulative bite curve between and within person RMSE - MEALS}
library(reshape2)

ID = unique(Meal_Event_in_percentage_interval_10$ParID)
RMSE_int10_meal = data.frame(matrix(rep(NA,8*length(ID)),ncol = 8))
names(RMSE_int10_meal) = c("ParID", "nsess","within_RMSE","between_RMSE","within_RMSE_scaled",
                      "between_RMSE_scaled","within_RMSE_prop","between_RMSE_prop")

for (i in 1:length(ID)) {
  dat = Meal_Event_in_percentage_interval_10[Meal_Event_in_percentage_interval_10$ParID == ID[i],]
  nsess = length(unique(dat$session))
  RMSE_int10_meal[i,"ParID"] = as.character(ID[i])
  RMSE_int10_meal[i,"nsess"] = nsess
  
  if (nsess > 1) {
    btw_RMSE_vector = NA
    btw_RMSE_vector_scaled = NA
    btw_RMSE_vector_prop = NA
    
    Bite_cum_1 = dat[dat$session == 1, "EventCount_cumulative"]
    Bite_cum_2 = dat[dat$session == 2, "EventCount_cumulative"]
    within_rmse_1.2 = sqrt(mean((Bite_cum_1 - Bite_cum_2)^2))
    within_rmse_1.2_prop = sqrt(mean(((Bite_cum_1/Bite_cum_1[10]) - (Bite_cum_2/Bite_cum_2[10]))^2))
    
    if (nsess == 2) {
      avg_within_RMSE = within_rmse_1.2
      avg_within_RMSE_scaled = within_rmse_1.2/abs(Bite_cum_1[10] - Bite_cum_2[10])
      avg_within_RMSE_prop = within_rmse_1.2_prop
      
      
    } else if (nsess == 3) {
      Bite_cum_3 = dat[dat$session == 3, "EventCount_cumulative"]
      within_rmse_1.3 = sqrt(mean((Bite_cum_1 - Bite_cum_3)^2))
      within_rmse_2.3 = sqrt(mean((Bite_cum_2 - Bite_cum_3)^2))
      
      within_rmse_1.3_prop = sqrt(mean(((Bite_cum_1/Bite_cum_1[10]) - (Bite_cum_3/Bite_cum_3[10]))^2))
      within_rmse_2.3_prop = sqrt(mean(((Bite_cum_2/Bite_cum_2[10]) - (Bite_cum_3/Bite_cum_3[10]))^2))
      
      
      avg_within_RMSE = mean(within_rmse_1.2, within_rmse_1.3, within_rmse_2.3)
      avg_within_RMSE_prop = mean(within_rmse_1.2_prop, within_rmse_1.3_prop, within_rmse_2.3_prop)
      avg_within_RMSE_scaled = mean(within_rmse_1.2/abs(Bite_cum_1[10] - Bite_cum_2[10]), 
                                    within_rmse_1.3/abs(Bite_cum_1[10] - Bite_cum_3[10]), 
                                    within_rmse_2.3/abs(Bite_cum_2[10] - Bite_cum_3[10]))
      
      
    }
    RMSE_int10_meal[i,"within_RMSE"] = avg_within_RMSE
    RMSE_int10_meal[i,"within_RMSE_scaled"] = avg_within_RMSE_scaled
    RMSE_int10_meal[i,"within_RMSE_prop"] = avg_within_RMSE_prop
    
    dat_other = Meal_Event_in_percentage_interval_10[Meal_Event_in_percentage_interval_10$ParID != ID[i],]
    dat_other_wide = dcast(dat_other, IntNum ~ ParID + session, value.var = "EventCount_cumulative")
    n_other = ncol(dat_other_wide)
    
    for (s in 1:nsess) {
      # By session average RMSE
      #btw_RMSE_vector = NA
      for (c in 2:n_other) {
        Bite_cum = dat[dat$session == s, "EventCount_cumulative"]
        Bite_cum_other = dat_other_wide[,c]
        btw_RMSE = sqrt(mean((Bite_cum - Bite_cum_other)^2))
        btw_RMSE_scaled = btw_RMSE/abs(Bite_cum[10] - Bite_cum_other[10])
        btw_RMSE_prop = sqrt(mean(((Bite_cum/Bite_cum[10]) - (Bite_cum_other/Bite_cum_other[10]))^2))
        
        #add to vector
        btw_RMSE_vector[c-1] = btw_RMSE
        btw_RMSE_vector_scaled[c-1] = btw_RMSE_scaled
        btw_RMSE_vector_prop[c-1] = btw_RMSE_prop
      }
      #RMSE_int10[i,"between_RMSE_sess"] = mean(btw_RMSE_vector)
    }
    RMSE_int10_meal[i,"between_RMSE"] = mean(btw_RMSE_vector)
    RMSE_int10_meal[i,"between_RMSE_scaled"] = mean(btw_RMSE_vector_scaled)
    RMSE_int10_meal[i,"between_RMSE_prop"] = mean(btw_RMSE_vector_prop)
  }
  
}


```

```{r cumulative bite curve between and within person RMSE - SNACKS}
library(reshape2)

# remove subject 0043
Snack_Event_in_percentage_interval_10_no0043 <- Snack_Event_in_percentage_interval_10[!(Snack_Event_in_percentage_interval_10$ParID == "AUR0043"),]

ID = unique(Snack_Event_in_percentage_interval_10_no0043$ParID)
RMSE_int10_snack = data.frame(matrix(rep(NA,8*length(ID)),ncol = 8))
names(RMSE_int10_snack) = c("ParID", "nsess","within_RMSE","between_RMSE","within_RMSE_scaled",
                      "between_RMSE_scaled","within_RMSE_prop","between_RMSE_prop")

for (i in 1:length(ID)) {
  dat = Snack_Event_in_percentage_interval_10_no0043[Snack_Event_in_percentage_interval_10_no0043$ParID == ID[i],]
  nsess = length(unique(dat$session))
  RMSE_int10_snack[i,"ParID"] = as.character(ID[i])
  RMSE_int10_snack[i,"nsess"] = nsess
  
  if (nsess > 1) {
    btw_RMSE_vector = NA
    btw_RMSE_vector_scaled = NA
    btw_RMSE_vector_prop = NA
    
    Bite_cum_1 = dat[dat$session == 1, "EventCount_cumulative"]
    Bite_cum_2 = dat[dat$session == 2, "EventCount_cumulative"]
    within_rmse_1.2 = sqrt(mean((Bite_cum_1 - Bite_cum_2)^2))
    within_rmse_1.2_prop = sqrt(mean(((Bite_cum_1/Bite_cum_1[10]) - (Bite_cum_2/Bite_cum_2[10]))^2))
    
    if (nsess == 2) {
      avg_within_RMSE = within_rmse_1.2
      avg_within_RMSE_scaled = within_rmse_1.2/abs(Bite_cum_1[10] - Bite_cum_2[10])
      avg_within_RMSE_prop = within_rmse_1.2_prop
      
      
    } else if (nsess == 3) {
      Bite_cum_3 = dat[dat$session == 3, "EventCount_cumulative"]
      within_rmse_1.3 = sqrt(mean((Bite_cum_1 - Bite_cum_3)^2))
      within_rmse_2.3 = sqrt(mean((Bite_cum_2 - Bite_cum_3)^2))
      
      within_rmse_1.3_prop = sqrt(mean(((Bite_cum_1/Bite_cum_1[10]) - (Bite_cum_3/Bite_cum_3[10]))^2))
      within_rmse_2.3_prop = sqrt(mean(((Bite_cum_2/Bite_cum_2[10]) - (Bite_cum_3/Bite_cum_3[10]))^2))
      
      
      avg_within_RMSE = mean(within_rmse_1.2, within_rmse_1.3, within_rmse_2.3)
      avg_within_RMSE_prop = mean(within_rmse_1.2_prop, within_rmse_1.3_prop, within_rmse_2.3_prop)
      avg_within_RMSE_scaled = mean(within_rmse_1.2/abs(Bite_cum_1[10] - Bite_cum_2[10]), 
                                    within_rmse_1.3/abs(Bite_cum_1[10] - Bite_cum_3[10]), 
                                    within_rmse_2.3/abs(Bite_cum_2[10] - Bite_cum_3[10]))
      
      
    }
    RMSE_int10_snack[i,"within_RMSE"] = avg_within_RMSE
    RMSE_int10_snack[i,"within_RMSE_scaled"] = avg_within_RMSE_scaled
    RMSE_int10_snack[i,"within_RMSE_prop"] = avg_within_RMSE_prop
    
    dat_other = Snack_Event_in_percentage_interval_10_no0043[Snack_Event_in_percentage_interval_10_no0043$ParID != ID[i],]
    dat_other_wide = dcast(dat_other, IntNum ~ ParID + session, value.var = "EventCount_cumulative")
    n_other = ncol(dat_other_wide)
    
    for (s in 1:nsess) {
      # By session average RMSE
      #btw_RMSE_vector = NA
      for (c in 2:n_other) {
        Bite_cum = dat[dat$session == s, "EventCount_cumulative"]
        Bite_cum_other = dat_other_wide[,c]
        btw_RMSE = sqrt(mean((Bite_cum - Bite_cum_other)^2))
        btw_RMSE_scaled = btw_RMSE/abs(Bite_cum[10] - Bite_cum_other[10])
        btw_RMSE_prop = sqrt(mean(((Bite_cum/Bite_cum[10]) - (Bite_cum_other/Bite_cum_other[10]))^2))
        
        #add to vector
        btw_RMSE_vector[c-1] = btw_RMSE
        btw_RMSE_vector_scaled[c-1] = btw_RMSE_scaled
        btw_RMSE_vector_prop[c-1] = btw_RMSE_prop
      }
      #RMSE_int10[i,"between_RMSE_sess"] = mean(btw_RMSE_vector)
    }
    RMSE_int10_snack[i,"between_RMSE"] = mean(btw_RMSE_vector)
    RMSE_int10_snack[i,"between_RMSE_scaled"] = mean(btw_RMSE_vector_scaled)
    RMSE_int10_snack[i,"between_RMSE_prop"] = mean(btw_RMSE_vector_prop)
  }
  
}


```
